### ISSUE TITLE
Package a release

### ISSUE THREAD

**Issue by flegfleg** [flotte-berlin/commons-booking-item-usage-restriction#2]
Hi fLotte-Team,
fantastic work, as always!
Do you maybe want to [pack a release](https://github.com/flotte-berlin/commons-booking-item-usage-restriction/releases) so this repository has a "download page" we can point users to? 

Best from Cologne!

**Comment by poilu** [comment]
Thanks for your appreciation! It took a while, but now it's done. :)

[Release v0.2.9](https://github.com/flotte-berlin/commons-booking-item-usage-restriction/releases/tag/v0.2.9)
